# Generated by Django 3.2.12 on 2022-03-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_group_userlog_userprofile'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='user',
            index_together={('username', 'phone')},
        ),
    ]
