# Generated by Django 3.2.12 on 2022-03-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, unique=True)),
                ('age', models.SmallIntegerField(default=0)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('info', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'index_together': {('username', 'phone')},
            },
        ),
    ]
